// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQT6fKFdx0Cvr2FnZcVu56JugniBaf9Lo',
    appId: '1:1042656988297:web:4f7e158cf9b3c1226f0a58',
    messagingSenderId: '1042656988297',
    projectId: 'fine-line-fb15f',
    authDomain: 'fine-line-fb15f.firebaseapp.com',
    storageBucket: 'fine-line-fb15f.firebasestorage.app',
    measurementId: 'G-WWQSJZCSH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHiMN-FnxH7j0Wp7rZH9TukMNSSY-w4Y',
    appId: '1:1042656988297:android:0e983a8fedf150b66f0a58',
    messagingSenderId: '1042656988297',
    projectId: 'fine-line-fb15f',
    storageBucket: 'fine-line-fb15f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKA74BYjyA587Sa2JVWpruZpg6EnfNsE',
    appId: '1:1042656988297:ios:92f1acdaf6b550116f0a58',
    messagingSenderId: '1042656988297',
    projectId: 'fine-line-fb15f',
    storageBucket: 'fine-line-fb15f.firebasestorage.app',
    iosBundleId: 'com.example.fineline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQT6fKFdx0Cvr2FnZcVu56JugniBaf9Lo',
    appId: '1:1042656988297:web:a36605afee0ea1746f0a58',
    messagingSenderId: '1042656988297',
    projectId: 'fine-line-fb15f',
    authDomain: 'fine-line-fb15f.firebaseapp.com',
    storageBucket: 'fine-line-fb15f.firebasestorage.app',
    measurementId: 'G-YS9X9Q9M37',
  );
}
